name: Build

on:
  push:
  pull_request:


permissions:
  contents: write

env: 
  CARGO_TERM_COLOR: always

jobs:
  release:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: simple-assembler 
          path: .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./simple-assembler
