name: Build and Release

on:
  push:
  pull_request:


permissions:
  contents: write

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: action/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose --release
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: kanash
          path: target/release/simple-assembler

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: simple-assembler 
          path: .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./simple-assembler
