
name: Publish to crates.io

on:
  release:
    types: [published, released]

jobs:
  push_to_crates_dot_io:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      attestations: write
      id-token: write
    steps:
        - uses: actions/checkout@v3
        - uses: actions-rs/toolchain@v1
          with:
              toolchain: stable
              override: true
        - uses: katyo/publish-crates@v2
          with:
              registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
